name: Gradle Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: |
        ./gradlew setupDecompWorkspace
        ./gradlew build
    - name: List files
      run: ls
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
       # Artifact name
       name: Salhack
       # A file, directory or wildcard pattern that describes what to upload
       path: ./build/libs/*-release.jar
